<div id = "information_image">
    <img src = "<?php echo config("resource_path") . "/fallback.gif" ?>">
</div>
<div id = "information_meta">
    <ul>
        <li>Singer 1</li>
        <li>Singer 2</li>
        <li>Singer 3</li>
    </ul>
    <ul>
        <li>Lyricist 1</li>
        <li>Lyricist 1</li>
    </ul>
    <p>From : Fallback Movie Name</p>
    <p>Length : 2:45s</p>
    <p>Company : T-series</p>
</div>
