<div class = "row" id = "random_spinner">
    <div class = "offset-by-one ten columns row">
        <?php require config("components_path") . "/spinnerelement.phtml"; ?>
        <?php require config("components_path") . "/spinnerelement.phtml"; ?>
        <?php require config("components_path") . "/spinnerelement.phtml"; ?>
        <?php require config("components_path") . "/spinnerelement.phtml"; ?>
    </div>
</div>
<div class = "row" id = "song_spinner">
    <div class = "offset-by-one ten columns row">
        <div class = "offset-by-one ten columns row">
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
        </div>
        <div class = "offset-by-one ten columns row">
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
            <?php require config("components_path") . "/spinnerelement.phtml"; ?>
        </div>
    </div>
</div>
